import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Movies from '../components/Movies'


export default function Home({movies}) {
  return (
    <>
      <Head>
        <title>Rimooves</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Movies data={movies}/>
      </main>
    </>
  )
}

export async function getStaticProps(){
    const res = await fetch("https://movies-database-gold.vercel.app/movies")
    const movies = await res.json()
    return {props:{
        movies,
    }}
} 